### ISSUE TITLE
Rewrite new images to OpenGL ES or something better than it

### ISSUE THREAD

**Issue by soundsnow** [ruffle-rs/ruffle-android#181]
Even more difficult than coding is drawing images. I knew that drawing lots of widgets with the Android graphic library would greatly reduce performance. So to rewrite the drawing to OpenGL ES or something better than it, performance improves rapidly.

**Comment by torokati44** [comment]
>  Ruffle Android Leader

I assume you mean me, but actually, at this point, this is az least as much @Dinnerbone's project as mine.

> I think I'm harassing him a lot and asking some pretty pointless questions.

While I wouldn't call it harassment, you do seem quite overzealous with expressing your ideas for the app, unfortunately in a way that doesn't make them directly useful.

> The truth is I still don't know what that Spinner actually is,

To be honest, I have no idea why you keep bringing it up either.

> So to rewrite the drawing to OpenGL ES or something better than it, performance improves rapidly.

I can imagine the current widgets are already rendered with hardware acceleration, but they certainly aren't a performance bottleneck at this point.

**Comment by torokati44** [comment]
Either way, this issue doesn't look actionable to me, as it's rather vague.
