### ISSUE TITLE
Problems installing Ruffle

### ISSUE THREAD

**Issue by BomberDuck** [ruffle-rs/ruffle-android#208]
This might just be a me problem, but whenever I try to install Ruffle, it either fails to parse the package or it says app not installed immediately after pressing install. I have more than enough storage space to have Ruffle, and no other apks that I've used have this problem. I've tried downloading newer versions and older versions and both have the same problem.

**Comment by torokati44** [comment]
What device is this on, with what Android version, and which APK are you trying to install?

**Comment by BomberDuck** [comment]
> What device is this on, with what Android version, and which APK are you trying to install?

**Comment by BomberDuck** [comment]
Retroid Pocket 2+, Android 9, and I've tried installing various apks, from the latest one, all the way to the first one. I've even tried installing the version that I previously had before.

**Comment by torokati44** [comment]
Android 8.0 and up should work... Are you trying to install the "universal" APK, or one of the ARM ones?

**Comment by BomberDuck** [comment]
That actually worked. Thanks, it was absolutely an issue on my part.

**Comment by torokati44** [comment]
Then you probably tried to install the 64 bit ARM build, when the device is 32 bit (or the other way around).
Glad it works now!
