### ISSUE TITLE
Can Ruffle be ported to HarmonyOS NEXT (also known as HarmonyOS 5.0)?

### ISSUE THREAD

**Issue by Alpa7000** [ruffle-rs/ruffle-android#346]
Since HarmonyOS NEXT removes native support for Android apps, and the only way to use Android apps on that platform is to use a virtualization solution called "Zuoyitong" ("卓易通" in Chinese). Zuoyitong itself has package name whitelist, user can not run Android apps outside whitelist. So Ruffle can no longer run on Huawei devices after upgraded to HarmonyOS NEXT.  Unfortunately, all Huawei smartphones shipped in 2025 and later will only preinstalled with HarmonyOS NEXT. Is it possible to develop Ruffle for HarmonyOS NEXT?

**Comment by adrian17** [comment]
AFAIK, none of the main devs knows anything about HarmonyOS, let alone its development environment :( (in fact, most of us weren't even aware it exists at all)

I don't think anyone here will be able to do anything with it (especially considering it seems oriented towards the China market), so it'd need some developer actually experienced in it to do it on their own (just like ruffle-android is mostly a one man project). In fact, from what I see, even Rust itself doesn't really document anything about the OS support.
So I imagine that until such a dev shows up, your best bet will be to use the web version ruffle via the browser :(

**Comment by UjuiUjuMandan** [comment]
Adobe has designated Flash's official successer just for China.

https://flash.cn
