### ISSUE TITLE
Can't enable `jpegxr` feature

### ISSUE THREAD

**Issue by torokati44** [ruffle-rs/ruffle-android#62]
The `jpegxr` feature (disabled by default in Ruffle) uses C/C++ code, and the build system doesn't find the cross-compiler for it correctly.

**Comment by Fancy2209** [comment]
Tested this in actions, seems to just not find `bits/wordsize.h`

**Comment by torokati44** [comment]
Yes, but that's just a symptom (also, only the first error of probably a lot more); not the root cause.

**Comment by Fancy2209** [comment]
Ah, my bad, just trying to check if I can figure out a fix
